server:
  port: 8448

spring:
  banner:
    charset: UTF-8
    location: classpath:xdu-chat-banner.txt

  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      idle-timeout: 600000
      max-lifetime: 1800000
      minimum-idle: 5
      maximum-pool-size: 10
      auto-commit: true
      pool-name: xdu-chat-pool
      connection-test-query: select 1
      connection-init-sql: select 1
      leak-detection-threshold: 2000
#      catalog: xdu_chat
      connection-timeout: 30000
      validation-timeout: 3000
    username: xdechat
    password: ZgDNPToXvd%YVZ!W
    url: jdbc:mysql://47.121.118.249:3306/xdechat?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true

mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

knife4j:
  enable: true
  openapi:
    title: xdu-chat代理与数据中台
    email: 22009200439@stu.xidian.edu.cn
    description: 用于对XDU-Chat进行数据转发和漫游的系统
    group:
      dev1:
        group-name: 开发一阶
        api-rule: package
    version: 0.1.0
    concat: 711lxsky